# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [1]:
# Import and ReadFile
import numpy as np
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
insurance_df = pd.read_csv(url)

In [2]:
# Your code here
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [3]:
insurance_clean_df = insurance_df.copy()

In [4]:
insurance_clean_df.columns = insurance_clean_df.columns.str.lower()
insurance_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   st                         1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer lifetime value    1068 non-null   object
 5   income                     1071 non-null   float64
 6   monthly premium auto       1071 non-null   float64
 7   number of open complaints  1071 non-null   object
 8   policy type                1071 non-null   object
 9   vehicle class              1071 non-null   object
 10  total claim amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [5]:
insurance_clean_df.columns = insurance_clean_df.columns.str.replace(" ", "_")

In [6]:
insurance_clean_df = insurance_clean_df.rename(columns= {"st": "state"})
insurance_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   object
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   object
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [7]:
# Your code here


insurance_clean_df["gender"].value_counts()

gender
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

In [8]:
insurance_clean_df["gender"] = insurance_clean_df["gender"].replace({
    "Male" : "M",
    "Female" : "F",
    "Femal" : "F",
    "female" : "F"
})

In [9]:
insurance_clean_df["gender"].value_counts()

gender
F    502
M    452
Name: count, dtype: int64

In [10]:
insurance_clean_df["state"].value_counts()

state
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [11]:
#need to clean Cali = California, WA as Washington and AZ as Arizona

insurance_clean_df["state"] = insurance_clean_df["state"].replace({
    "Cali" : "California",
    "WA" : "Washington", 
    "AZ" : "Arizona"

})

In [12]:
insurance_clean_df["state"].value_counts()

state
California    331
Oregon        320
Arizona       211
Washington    111
Nevada         98
Name: count, dtype: int64

In [13]:
insurance_clean_df["education"].value_counts()

education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

In [14]:
insurance_clean_df["education"] = insurance_clean_df["education"].replace({
    "Bachelors" : "Bachelor"
})

In [15]:
insurance_clean_df["customer_lifetime_value"] = insurance_clean_df["customer_lifetime_value"].str.replace("%", "", regex = False)

In [16]:
insurance_clean_df["customer_lifetime_value"].value_counts()

customer_lifetime_value
445811.34     4
251459.20     4
272535.64     3
578018.22     3
684615.03     3
             ..
245357.08     1
507566.27     1
321497.94     1
1227534.31    1
899704.02     1
Name: count, Length: 1027, dtype: int64

In [17]:
insurance_clean_df["vehicle_class"] = insurance_clean_df["vehicle_class"].replace({
    "Sports Car" : "Luxury",
    "Luxury Car" : "Luxury",
    "Luxury SUV" : "Luxury"
})
insurance_clean_df["vehicle_class"].value_counts()

vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Luxury            91
Name: count, dtype: int64

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [18]:
# Your code here

insurance_clean_df["customer_lifetime_value"] = pd.to_numeric(
    insurance_clean_df["customer_lifetime_value"], errors="coerce"
)

insurance_clean_df["number_of_open_complaints"] = insurance_clean_df["number_of_open_complaints"].str.split("/").str[1]

insurance_clean_df["number_of_open_complaints"] = pd.to_numeric(
    insurance_clean_df["number_of_open_complaints"], errors="coerce"
)

In [19]:
insurance_clean_df["customer_lifetime_value"]

0              NaN
1        697953.59
2       1288743.17
3        764586.18
4        536307.65
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: customer_lifetime_value, Length: 4008, dtype: float64

In [20]:
type(insurance_clean_df["customer_lifetime_value"][0])

numpy.float64

In [21]:
insurance_clean_df["number_of_open_complaints"].value_counts()

number_of_open_complaints
0.0    830
1.0    138
2.0     50
3.0     34
4.0     13
5.0      6
Name: count, dtype: int64

In [22]:
type(insurance_clean_df["number_of_open_complaints"][0])

numpy.float64

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [23]:
# Your code here

insurance_clean_df.isnull().sum()

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [24]:
insurance_clean_df[insurance_clean_df["customer"].isnull()]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
1071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
missing_customer_rows = insurance_clean_df[insurance_clean_df["customer"].isnull()]

for column in missing_customer_rows.columns:
    print(column, missing_customer_rows[column].notnull().sum())

customer 0
state 0
gender 0
education 0
customer_lifetime_value 0
income 0
monthly_premium_auto 0
number_of_open_complaints 0
policy_type 0
vehicle_class 0
total_claim_amount 0

In [26]:
#drop all the values in which we don't have customer 
insurance_clean_df = insurance_clean_df.dropna(subset=["customer"])

In [37]:
insurance_clean_df.shape

(1071, 11)

In [38]:
insurance_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     1071 non-null   object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 100.4+ KB

In [39]:
insurance_clean_df[insurance_clean_df["gender"].isnull()]

Empty DataFrame
Columns: [customer, state, gender, education, customer_lifetime_value, income, monthly_premium_auto, number_of_open_complaints, policy_type, vehicle_class, total_claim_amount]
Index: []

In [40]:
insurance_clean_df["gender"] = insurance_clean_df["gender"].fillna("Unknown")

In [41]:
insurance_clean_df["gender"].value_counts(dropna=False)

gender
F          502
M          452
Unknown    117
Name: count, dtype: int64

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [42]:
# Your code here
insurance_clean_df.duplicated().sum()

np.int64(0)

In [43]:
#There are no duplicates in the insurance_clean_df

In [44]:
insurance_noduplicates_df = insurance_df.copy()
insurance_noduplicates_df = insurance_noduplicates_df.drop_duplicates()
insurance_noduplicates_df.duplicated().sum()

np.int64(0)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [45]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [46]:
# Your code here