# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [82]:
# Your code here

import numpy as np
import pandas as pd

In [83]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
insurance_df = pd.read_csv(url)

In [84]:
insurance_df.shape
print (f'Number of rows: {insurance_df.shape[0]}, Number of columns: {insurance_df.shape[1]}')

Number of rows: 4008, Number of columns: 11

In [85]:
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [86]:
#Looking at the columns I understand that Customer Lifetime Value and Number of Open complaints data types should be integers not an objects 
#Step 1 check all the data, of 4008 rows only about 1071 appear to have values, based on the fact that customer is also only filled 1071 times, there might be only 1071 actual customers in out df
#Step 2 check nulls in the data we need to convert, nulls for Customer Lifetime Value, are just 3 suggesting there is no more value on those, number of open compaints are always filled, but 0 is not null, take that into perspective
#Change datatype for customer lifetime value to int  checking 3 reamining with value 0
#Change datatype for Number of Open complaints to int
#Change GENDER to Gender 
#Create Gender to non-null, N/A (maybe)


#We will create a new DataBase to work on

In [87]:
insurance_clean_df = insurance_df.copy()

In [88]:
insurance_clean_df.isnull().sum()

Customer                     2937
ST                           2937
GENDER                       3054
Education                    2937
Customer Lifetime Value      2940
Income                       2937
Monthly Premium Auto         2937
Number of Open Complaints    2937
Policy Type                  2937
Vehicle Class                2937
Total Claim Amount           2937
dtype: int64

In [89]:
insurance_clean_df[insurance_clean_df["Customer"].isnull()]

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
1071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
insurance_clean_df[insurance_clean_df["Customer"].isnull()].isnull().sum(axis=1)

1071    11
1072    11
1073    11
1074    11
1075    11
        ..
4003    11
4004    11
4005    11
4006    11
4007    11
Length: 2937, dtype: int64

In [91]:
for column in insurance_clean_df:
    if insurance_clean_df[column].isnull().sum() < insurance_clean_df["Customer"].isnull().sum():
        print ("You should not drop all rows with no Customer value")
    else:
        print ("You can drop all rows with no Customer Value, they're all empty")

You can drop all rows with no Customer Value, they're all empty
You can drop all rows with no Customer Value, they're all empty
You can drop all rows with no Customer Value, they're all empty
You can drop all rows with no Customer Value, they're all empty
You can drop all rows with no Customer Value, they're all empty
You can drop all rows with no Customer Value, they're all empty
You can drop all rows with no Customer Value, they're all empty
You can drop all rows with no Customer Value, they're all empty
You can drop all rows with no Customer Value, they're all empty
You can drop all rows with no Customer Value, they're all empty
You can drop all rows with no Customer Value, they're all empty

In [92]:
missing_customer_rows = insurance_clean_df[insurance_clean_df["Customer"].isnull()]

for column in missing_customer_rows.columns:
    print(column, missing_customer_rows[column].notnull().sum())

Customer 0
ST 0
GENDER 0
Education 0
Customer Lifetime Value 0
Income 0
Monthly Premium Auto 0
Number of Open Complaints 0
Policy Type 0
Vehicle Class 0
Total Claim Amount 0

In [93]:
#drop all the values in which we don't have customer 
insurance_clean_df = insurance_clean_df.dropna(subset=["Customer"])

In [94]:
insurance_clean_df.shape

(1071, 11)

In [95]:
insurance_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 100.4+ KB

In [96]:
insurance_clean_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [97]:
###Appropiate nature for the value:
#Customer - is an ID, Object, yes
#ST - is a State, object, yes
#Gender, is an object. yes
#Education - is an object, yes
#Customer Lifetime Value - this should be a float it's a % for some reason, might need to /100
#Income is a float, yes
#Monthly Premium Auto is a float, yes
#Number of open complaints - this should be a float but the format is weird there might be a reason for it to be an object
#Policy type is an object, yes
#Vehicle class is an oject, yes
#Total Claim amount is a float, yes

In [98]:
#Identify number of unique variables

insurance_clean_df.nunique()

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

In [99]:
#Categorical are: Customer ST, Gender, Education,  policy type, Vehicle class
#Numerical are : Customer Lifetime Value, Income, Monthly premium Auto, Total Claim amount

In [100]:
#Customer Lifetime Value appears to be stored with incorrect percentage formatting. 
# Since CLV represents monetary value, I removed the % symbol and divided by 100. 
# The resulting values range from about 2,004 to 58,167, which is more realistic when compared with monthly premiums and customer income.





#I'll turn Customer Lifetime Value into a float

insurance_clean_df["Customer Lifetime Value"] = insurance_clean_df["Customer Lifetime Value"].str.replace("%", "", regex = False).astype(float)/100

In [101]:
insurance_clean_df.describe()

,Customer Lifetime Value,Income,Monthly Premium Auto,Total Claim Amount
count,1068.000000,1071.000000,1071.000000,1071.000000
mean,7936.902593,39295.701214,193.234360,404.986909
std,6434.784103,30469.427060,1601.190369,293.027260
min,2004.350700,0.000000,61.000000,0.382107
25%,4034.079950,14072.000000,68.000000,202.157702
50%,5881.742350,36234.000000,83.000000,354.729129
75%,8962.871975,64631.000000,109.500000,532.800000
max,58166.553500,99960.000000,35354.000000,2893.239678

In [102]:
"""ST has 8 unique values, but some values may need cleaning if abbreviations and full state names are mixed.
GENDER has inconsistent labels, such as F, M, Male, Femal, and NaN, so it should be standardized.
Education has 6 categories and represents customer education level.
Policy Type has 3 categories, which makes it easy to compare policy groups.
Vehicle Class has 6 categories, representing different types of insured vehicles.

Customer Lifetime Value has a wide range, meaning some customers are much more valuable than others.
Income ranges from 0 to 99,960. The 0 values may represent missing income or customers with no income.
Monthly Premium Auto has a very large maximum compared with the median, so there may be an outlier.
Total Claim Amount also varies widely, showing that some customers claimed much more than others.
"""

'ST has 8 unique values, but some values may need cleaning if abbreviations and full state names are mixed.\nGENDER has inconsistent labels, such as F, M, Male, Femal, and NaN, so it should be standardized.\nEducation has 6 categories and represents customer education level.\nPolicy Type has 3 categories, which makes it easy to compare policy groups.\nVehicle Class has 6 categories, representing different types of insured vehicles.\n\nCustomer Lifetime Value has a wide range, meaning some customers are much more valuable than others.\nIncome ranges from 0 to 99,960. The 0 values may represent missing income or customers with no income.\nMonthly Premium Auto has a very large maximum compared with the median, so there may be an outlier.\nTotal Claim Amount also varies widely, showing that some customers claimed much more than others.\n'

In [103]:
#Let's fix GENDER
#First let's change it to Gender

insurance_clean_df = insurance_clean_df.rename(columns={"GENDER": "Gender"})

In [104]:
#Now, let's see the options and standarize
insurance_clean_df["Gender"].value_counts()

Gender
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

In [105]:
insurance_clean_df["Gender"] = insurance_clean_df["Gender"].replace({
    "Male" : "M",
    "Female" : "F",
    "Femal" : "F",
    "female" : "F"
})

In [106]:
insurance_clean_df["Gender"].value_counts()

Gender
F    502
M    452
Name: count, dtype: int64

In [107]:
#Number of Open Complaints is not giving accurate Data, must be the middle number the actual number of open complaints
#Cleaning below and turning into int

insurance_clean_df["Number of Open Complaints"] = insurance_clean_df["Number of Open Complaints"].str.split("/").str[1].astype(int)

In [108]:
insurance_clean_df["Number of Open Complaints"].value_counts()

Number of Open Complaints
0    830
1    138
2     50
3     34
4     13
5      6
Name: count, dtype: int64

In [109]:
insurance_clean_df.describe()

,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount
count,1068.000000,1071.000000,1071.000000,1071.000000,1071.000000
mean,7936.902593,39295.701214,193.234360,0.394024,404.986909
std,6434.784103,30469.427060,1601.190369,0.883769,293.027260
min,2004.350700,0.000000,61.000000,0.000000,0.382107
25%,4034.079950,14072.000000,68.000000,0.000000,202.157702
50%,5881.742350,36234.000000,83.000000,0.000000,354.729129
75%,8962.871975,64631.000000,109.500000,0.000000,532.800000
max,58166.553500,99960.000000,35354.000000,5.000000,2893.239678

In [110]:
numerical_cols = [
    "Customer Lifetime Value",
    "Income",
    "Monthly Premium Auto",
    "Number of Open Complaints",
    "Total Claim Amount"
]

insurance_clean_df[numerical_cols].mode()

,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount
0,2514.5920,0.0,65.0,0.0,321.6
1,4458.1134,NaN,NaN,NaN,NaN

In [111]:
insurance_clean_df.describe(include="object")

       Customer      ST Gender Education    Policy Type  Vehicle Class
count      1071    1071    954      1071           1071           1071
unique     1071       8      2         6              3              6
top     RB50392  Oregon      F  Bachelor  Personal Auto  Four-Door Car
freq          1     320    502       324            780            576

In [112]:
categorical_cols = ["ST", "Gender", "Education", "Policy Type", "Vehicle Class"]

for col in categorical_cols:
    print(col)
    print(insurance_clean_df[col].value_counts(dropna=False))
    print()

ST
ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

Gender
Gender
F      502
M      452
NaN    117
Name: count, dtype: int64

Education
Education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

Policy Type
Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

Vehicle Class
Vehicle Class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

In [113]:
""" 

Looking at mean and the 50% we see the great majority of the Customer value is actually quite low.
Some customers are really on the premium side but very few - which correlates with the income and premiums

Total Claim refers to the history of claims rather than the value sum of the open claims
Most CUstomers don't have complaints open


"""

" \n\nLooking at mean and the 50% we see the great majority of the Customer value is actually quite low.\nSome customers are really on the premium side but very few - which correlates with the income and premiums\n\nTotal Claim refers to the history of claims rather than the value sum of the open claims\nMost CUstomers don't have complaints open\n\n\n"

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [114]:
"""

I should clean it before I can use it, but I don't know how


"""

"\n\nI should clean it before I can use it, but I don't know how\n\n\n"

In [115]:
# Your code here

insurance_clean_df ["ST"].value_counts()

ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [116]:
insurance_clean_df["ST"].value_counts(ascending=True).head(5)

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [117]:
# Your code here

policy_counts = insurance_clean_df["Policy Type"].value_counts()
print(policy_counts)
print()

policy_label_max = insurance_clean_df["Policy Type"].value_counts().idxmax()
policy_number_max = insurance_clean_df["Policy Type"].value_counts().max()

print(policy_label_max, policy_number_max)

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

Personal Auto 780

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [118]:
# Your code here

insurance_personal = insurance_clean_df.loc [insurance_clean_df["Policy Type"] == "Personal Auto"] 
insurance_corporate = insurance_clean_df.loc[insurance_clean_df["Policy Type"] == "Corporate Auto"] 

personal_avg_income = insurance_personal["Income"].mean()
corporate_avg_income = insurance_corporate["Income"].mean()
print()



print(f""" Personal Auto insurance holders have an average income of {round(personal_avg_income,2)}, 
while Corporate Auto insurance holders have an average income of {round(corporate_avg_income,2)} """)
print()

if personal_avg_income <  corporate_avg_income:
    print("Yes, Customers with Personal Auto have a lower income")
else: 
    print("No, Customers with Personal Auto don't have a lower income")

 Personal Auto insurance holders have an average income of 38180.7,
while Corporate Auto insurance holders have an average income of 41390.31

Yes, Customers with Personal Auto have a lower income

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [119]:
# Your code here


insurance_clean_df.describe()

,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount
count,1068.000000,1071.000000,1071.000000,1071.000000,1071.000000
mean,7936.902593,39295.701214,193.234360,0.394024,404.986909
std,6434.784103,30469.427060,1601.190369,0.883769,293.027260
min,2004.350700,0.000000,61.000000,0.000000,0.382107
25%,4034.079950,14072.000000,68.000000,0.000000,202.157702
50%,5881.742350,36234.000000,83.000000,0.000000,354.729129
75%,8962.871975,64631.000000,109.500000,0.000000,532.800000
max,58166.553500,99960.000000,35354.000000,5.000000,2893.239678

In [120]:
top_25_claim_amount = insurance_clean_df.loc[insurance_clean_df["Total Claim Amount"] > 532.80]
top_25_claim_amount.info()

<class 'pandas.core.frame.DataFrame'>
Index: 264 entries, 1 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   264 non-null    object
 1   ST                         264 non-null    object
 2   Gender                     238 non-null    object
 3   Education                  264 non-null    object
 4   Customer Lifetime Value    264 non-null    float64
 5   Income                     264 non-null    float64
 6   Monthly Premium Auto       264 non-null    float64
 7   Number of Open Complaints  264 non-null    int64
 8   Policy Type                264 non-null    object
 9   Vehicle Class              264 non-null    object
 10  Total Claim Amount         264 non-null    float64
dtypes: float64(4), int64(1), object(6)
memory usage: 24.8+ KB

In [121]:
top_25_claim_amount.describe()

,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount
count,264.000000,264.000000,264.000000,264.000000,264.000000
mean,9086.868131,23677.344697,165.193182,0.416667,782.228263
std,6387.677898,27013.483721,623.930992,0.943593,292.751640
min,2287.596900,0.000000,63.000000,0.000000,537.600000
25%,4723.957925,0.000000,99.000000,0.000000,606.521741
50%,7781.768250,18807.000000,114.000000,0.000000,679.597985
75%,10544.299275,42423.750000,133.250000,0.000000,851.400000
max,38445.855900,99316.000000,10202.000000,5.000000,2893.239678